vue-django/DjTodo/todo/urls.py
from django.urls import path
from . import views


app_name = 'todo'
urlpatterns = [
    path('vonly/', views.TodoVueOnlyTV.as_view(), name='vonly'),

    path('create/', views.TodoCV.as_view(), name='create'),
    path('list/', views.TodoLV.as_view(), name='list'),
    path('<int:pk>/delete/', views.TodoDelV.as_view(), name='delete'),
    path('<int:pk>/delete2/', views.TodoDelV2.as_view(), name='delete2'),
    path('mixin/', views.TodoMOMCV.as_view(), name='mixin'),
]

vue-django/DjTodo/todo/views.py
from django.views.generic import TemplateView, CreateView, ListView, DeleteView
from django.views.generic.list import MultipleObjectMixin
from django.urls import reverse_lazy

from todo.models import Todo

# Create your views here.
class TodoVueOnlyTV(TemplateView):
    template_name = 'todo/todo_vue_only.html'


class TodoCV(CreateView):
    model = Todo
    fields = '__all__'
    template_name = 'todo/todo_form.html'
    success_url = reverse_lazy('todo:list')


class TodoLV(ListView):
    model = Todo
    template_name = 'todo/todo_list.html'


class TodoDelV(DeleteView):
    model = Todo
    template_name = 'todo/todo_confirm_delete.html'
    success_url = reverse_lazy('todo:list')

class TodoMOMCV(MultipleObjectMixin, CreateView):
    model = Todo
    fields = '__all__'
    template_name = 'todo/todo_form_list.html'
    success_url = reverse_lazy('todo:mixin')

    def get(self, request, *args, **kwargs):
        self.object_list = self.get_queryset()
        return super().get(request, *args, **kwargs)
    
    def post(self, request, *args, **kwargs):
        self.object_list = self.get_queryset()
        return super().post(request, *args, **kwargs)

class TodoDelV2(DeleteView):
    model = Todo

    # get request가 들어왔을 때 바로 삭제하게 만들었으므로 form이 불필요하니 아래 template_name 을 주석 처리
    #template_name = 'todo/todo_confirm_delete.html'
    success_url = reverse_lazy('todo:mixin')

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

vue-django/DjTodo/todo/templates/todo/todo_confirm_delete.html
{% extends 'base.html' %}

{% block title %}todo_confirm_delete.html{% endblock %}

{% block extra-style %}
    <style>
        body {
            text-align: center;
            background-color: #ddd;
        }
        .inputBox {
            margin: auto;
            width: 70%;
            background: white;
            height: 50px;
            border-radius: 50px;
            line-height: 50px;
        }
        .inputBox .name {
            border-style: none;
            border-bottom: 1px solid #ddd;
            width: 70px;
            padding-left: 20px;
        }
        .inputBox .item {
            border-style: none;
            border-bottom: 1px solid #ddd;
            width: 400px;
            margin-left: 50px;
            padding-left: 20px;
        }
        .todoList {
            list-style: none;
            padding: 10px 0;
            text-align: left;
        }
        .todoList li {
            display: flex;
            height: 50px;
            line-height: 50px;
            margin: 0.5rem 0;
            padding: 0 0.9rem;
            background: white;
            border-radius: 5px;
        }
        .removeBtn {
            margin-left: auto;
            font-size: 20px;
        }
    </style>
{% endblock %}

{% block content %}
    <div id = 'app'>

        <h1> Todo Delete </h1>
        <p>Are you sure to delete {{ object }} ? </p>
        <br>

        <form action="." method="post"> {% csrf_token %}
            <button type="submit" class="btn btn-danger btn-sm">Confirms</button>
        </form>

    </div>
{% endblock %}

vue-django/DjTodo/todo/templates/todo/todo_form.html
{% extends 'base.html' %}

{% block title %}todo_form.html{% endblock %}

{% block extra-style %}
    <style>
        body {
            text-align: center;
            background-color: #ddd;
        }
        .inputBox {
            margin: auto;
            width: 70%;
            background: white;
            height: 50px;
            border-radius: 50px;
            line-height: 50px;
        }
        .inputBox .name {
            border-style: none;
            border-bottom: 1px solid #ddd;
            width: 90px;
            padding-left: 20px;
            line-height: 20px;
        }
        .inputBox .item {
            border-style: none;
            border-bottom: 1px solid #ddd;
            width: 400px;
            margin-left: 50px;
            padding-left: 20px;
            line-height: 20px;
        }
        .todoList {
            list-style: none;
            padding: 10px 0;
            text-align: left;
        }
        .todoList li {
            display: flex;
            height: 50px;
            line-height: 50px;
            margin: 0.5rem 0;
            padding: 0 0.9rem;
            background: white;
            border-radius: 5px;
        }
        .removeBtn {
            margin-left: auto;
            font-size: 20px;
        }
    </style>
{% endblock %}

{% block content %}
    <div id = 'app'>

        <h1>My Todo App !</h1>
        <strong>서로 할 일이나 의견을 공유해 봅시다.</strong>
        <br>

        <form class="inputBox" action='.' method="post"> {% csrf_token %}
            <input class="name" name="name" type="text" placeholder="name ...">
            <input class="item" name="todo" type="text" 
                placeholder="type anything welcomed ...">
            <button type="submit" class="btn btn-info btn-sm">ADD</button>
        </form>
    </div>
{% endblock %}

vue-django/DjTodo/todo/templates/todo/todo_form_list.html
{% extends 'base.html' %}

{% block title %}todo_form.html{% endblock %}

{% block extra-style %}
    <style>
        body {
            text-align: center;
            background-color: #ddd;
        }
        .inputBox {
            margin: auto;
            width: 70%;
            background: white;
            height: 50px;
            border-radius: 50px;
            line-height: 50px;
        }
        .inputBox .name {
            border-style: none;
            border-bottom: 1px solid #ddd;
            width: 90px;
            padding-left: 20px;
            line-height: 20px;
        }
        .inputBox .item {
            border-style: none;
            border-bottom: 1px solid #ddd;
            width: 400px;
            margin-left: 50px;
            padding-left: 20px;
            line-height: 20px;
        }
        .todoList {
            list-style: none;
            padding: 10px 0;
            text-align: left;
        }
        .todoList li {
            display: flex;
            height: 50px;
            line-height: 50px;
            margin: 0.5rem 0;
            padding: 0 0.9rem;
            background: white;
            border-radius: 5px;
        }
        .removeBtn {
            margin-left: auto;
            font-size: 20px;
        }
        .removeBtn:hover{
            color:red;
        }
        .modal-footer a {
            color:white;
        }
    </style>
{% endblock %}

{% block content %}
    <div id = 'app'>

        <h1>My Todo App !</h1>
        <strong>서로 할 일이나 의견을 공유해 봅시다.</strong>
        <br>

        <form class="inputBox" action='.' method="post"> {% csrf_token %}
            <input class="name" name="name" type="text" placeholder="name ...">
            <input class="item" name="todo" type="text" 
                placeholder="type anything welcomed ...">
            <button type="submit" class="btn btn-info btn-sm">ADD</button>
        </form>

        <ul class="todoList">
            {% for todo in object_list %}
            <li>
                <span>{{ todo.name }}:: {{ todo.todo }}</span>
                <span class="removeBtn" data-toggle="modal" data-target="#myModal"
                 data-id="{{todo.id}}" data-name="{{todo.name}}" data-todo="{{todo.todo}}">&#x00D7</a></span>
            </li>
            {% endfor %}
        </ul>
        <!-- Modal -->
        <div class="modal" id="myModal" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Are you sure to delete ?</h5>
                    </div>
                    <div class="modal-body">
                        body-text
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary btn-sm" data-dismiss="modal">Cancel</button>
                        <button type="button" class="btn btn-danger btn-sm">
                            <a href="">Delete</a></button>
                    </div>
                </div>
            </div>
        </div>

    </div>
{% endblock %}

{% block extra-script %}
<script>
$('#myModal').on('show.bs.modal', function (event) {
    var button = $(event.relatedTarget)
    var id = button.data('id')
    var name = button.data('name')
    var todo = button.data('todo')

    var modal = $(this)
    modal.find('.modal-body').text(name + '::: ' + todo)
    modal.find('.modal-footer a').attr('href', '/todo/' + id + '/delete2/')
})
</script>
{% endblock %}

vue-django/DjTodo/todo/templates/todo/todo_list.html
{% extends 'base.html' %}

{% block title %} todo_list.html{% endblock %}

{% block extra-style %}
    <style>
        body {
            text-align: center;
            background-color: #ddd;
        }
        .inputBox {
            margin: auto;
            width: 70%;
            background: white;
            height: 50px;
            border-radius: 50px;
            line-height: 50px;
        }
        .inputBox .name {
            border-style: none;
            border-bottom: 1px solid #ddd;
            width: 70px;
            padding-left: 20px;
        }
        .inputBox .item {
            border-style: none;
            border-bottom: 1px solid #ddd;
            width: 400px;
            margin-left: 50px;
            padding-left: 20px;
        }
        .todoList {
            list-style: none;
            padding: 10px 0;
            text-align: left;
        }
        .todoList li {
            display: flex;
            height: 50px;
            line-height: 50px;
            margin: 0.5rem 0;
            padding: 0 0.9rem;
            background: white;
            border-radius: 5px;
        }
        .removeBtn {
            margin-left: auto;
            font-size: 20px;
        }
    </style>
{% endblock %}
{% block content %}
    <div id = 'app'>

        <h1>My Todo App !</h1>
        <strong>서로 할 일이나 의견을 공유해 봅시다.</strong>
        <br>

    
        <ul class="todoList">
            {% for todo in object_list %}
            <li>
                <span>{{ todo.name }}:: {{ todo.todo }}</span>
                <span class="removeBtn"><a href="{% url 'todo:delete' todo.id %}">&#x00D7</a></span>
            </li>
            {% endfor %}
        </ul>

    </div>
{% endblock %}

vue-django/DjTodo/todo/templates/todo/todo_vue_only.html
{% extends 'base.html' %}

{% block title %}todo_vue_only.html {% endblock %}

{% block extra-style %}
    <style>
        body {
            text-align: center;
            background-color: #ddd;
        }
        .inputBox {
            margin: auto;
            width: 70%;
            background: white;
            height: 50px;
            border-radius: 50px;
            line-height: 50px;
        }
        .inputBox .name {
            border-style: none;
            border-bottom: 1px solid #ddd;
            width: 90px;
            padding-left: 20px;
            line-height: 20px;
        }
        .inputBox .item {
            border-style: none;
            border-bottom: 1px solid #ddd;
            width: 400px;
            margin-left: 50px;
            padding-left: 20px;
            line-height: 20px;
        }
        .todoList {
            list-style: none;
            padding: 10px 0;
            text-align: left;
        }
        .todoList li {
            display: flex;
            height: 50px;
            line-height: 50px;
            margin: 0.5rem 0;
            padding: 0 0.9rem;
            background: white;
            border-radius: 5px;
        }
        .removeBtn {
            margin-left: auto;
            font-size: 20px;
        }
    </style>
{% endblock %}

{% block content %}
    <div id = 'app'>

        <h1>My Todo App !</h1>
        <strong>서로 할 일이나 의견을 공유해 봅시다.</strong>
        <br>

        <div class="inputBox">
            <input class="name" v-model="name" type="text" placeholder="name ...">
            <input class="item" v-model="newTodoItem" type="text" 
                v-on:keyup.enter="add_todo()" placeholder="type anything welcomed ...">
            <button v-on:click="add_todo()" class="btn btn-primary btn-sm">ADD</button>
        </div>
    
        <ul class="todoList">
            <li v-for="(todo, index) in todoItems">
                <span>{ todo.name }:: {todo.item}</span>
                <span class="removeBtn" v-on:click="remove_todo(index)">&#x00D7</span>
            </li>
        </ul>

    </div>
{% endblock %}

{% block extra-script %}
    <script src="https://unpkg.com/vue/dist/vue.min.js"></script>
    <script>
        var vm = new Vue({
            el: '#app',
            delimiters: ['{', '}'],
            data: {
                name:'',
                newTodoItem:'',
                todoItems:[
                    {name:'김석훈', item:'Django와 Vue.js 연동 프로그램을 만들고 있습니다.'},
                    {name:'홍길동', item:'이름을 안쓰면 홍길동으로 나와요...'},
                    {name:'이순신', item:'신에게는 아직 열두 척의 배가 있사옵니다.'},
                    {name:'성춘형', item:'그네 타기'},
                ],
            },
            methods: {
                add_todo: function(){
                    console.log("add_todo()...");
                    if(this.name == '') this.name = '홍길동';
                    if(this.newTodoItem == '') return;

                    this.todoItems.push({name: this.name, item:this.newTodoItem});

                    this.name = '';
                    this.newTodoItem = '';
                },
                remove_todo: function(index){
                    console.log("remove_todo()...");
                    this.todoItems.splice(index, 1);
                }
            },
        })
    </script>
{% endblock %}