vue-django/VueDjTodo/api/urls.py
from django.urls import path
from . import views

#app_name 스페이는 api로 하였음.
app_name = 'api'
urlpatterns = [
    path('todo/list/', views.ApiTodoLV.as_view(), name = 'list'),
    path('todo/<int:pk>/delete/', views.ApiTodoDelV.as_view(), name='delete'),
    path('todo/create/', views.ApiTodoCV.as_view(), name='create'),
]

vue-django/VueDjTodo/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', views.HomeView.as_view(), name='home'),
    path('todo/', include('todo.urls')),
    path('api/', include('api.urls')),
]

vue-django/VueDjTodo/todo/urls.py
from django.urls import path

from . import views

app_name = 'todo'
urlpatterns = [
    path('', views.TodoTV.as_view(), name='index'),
]

vue-django/VueDjTodo/todo/models.py
from django.db import models

# Create your models here.
class Todo(models.Model):
    name = models.CharField('NAME', max_length=5, blank=True)
    todo = models.CharField('TODO', max_length=50)

    def __str__(self):
        return self.todo

    def save(self, force_insert=False, using=None, update_fields=None):
        if not self.name:
            self.name = "홍길동"
        super().save()

vue-django/VueDjTodo/api/views.py
from django.http import JsonResponse
from django.views.generic import ListView, DeleteView
from django.views.generic.list import BaseListView
from django.views.generic.edit import BaseDeleteView, BaseCreateView
# Create your views here.
from django.views.decorators.csrf import csrf_exempt, ensure_csrf_cookie
from django.utils.decorators import method_decorator
from todo.models import Todo
import json
from django.forms.models import model_to_dict

@method_decorator(ensure_csrf_cookie, name='dispatch')
class ApiTodoLV(BaseListView):
    model = Todo
    # template_name 속성은 보여줄 html 파일이 있을때 쓰는 속성인대, 지금 json response를 할 것이기에 이 경우는 보여줄 html이 없기 때문에 안씀
    # template_name
    
    # #client에서 get 방식으로 요청을 보낼 때
    # def get(self, request, *args, **kwargs):
    #     tmpList = [
    #                 {'id':1, 'name':'d김석훈', 'todo':'Django와 Vue.js 연동 프로그램을 만들고 있습니다.'},
    #                 {'id':2, 'name':'d홍길동', 'todo':'이름을 안쓰면 홍길동으로 나와요...'},
    #                 {'id':3, 'name':'d이순신', 'todo':'신에게는 아직 열두 척의 배가 있사옵니다.'},
    #                 {'id':4, 'name':'d성춘형', 'todo':'그네 타기'},
    #                 ]
    #     return JsonResponse(data=tmpList, safe=False)

    def render_to_response(self, context, **response_kwargs):
        todoList = list(context['object_list'].values())
        return JsonResponse(data=todoList, safe=False)

#@method_decorator(csrf_exempt, name='dispatch')
class ApiTodoDelV(BaseDeleteView):
    model = Todo

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.delete()
        return JsonResponse(data={}, safe=True, status=204)

#@method_decorator(csrf_exempt, name='dispatch')
class ApiTodoCV(BaseCreateView):
    model = Todo
    fields = '__all__'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['data'] = json.loads(self.request.body)
        return kwargs

    def form_valid(self, form):
        print("form_valid()", form)
        self.object = form.save()
        newTodo = model_to_dict(self.object)
        print(f"newTodo: {newTodo}")
        return JsonResponse(data=newTodo, status=201)

    def form_invalid(self, form):
        print("form_invalid()", form)
        print("form_invalid()", self.request.POST)
        print("form_invalid()", self.request.body.decode('utf8'))
        return JsonResponse(data=form.errors, status=400)

vue-django/VueDjTodo/mysite/views.py
from django.views.generic import TemplateView

class HomeView(TemplateView):
    template_name = 'home.html'

vue-django/VueDjTodo/todo/views.py
from django.views.generic import TemplateView

class TodoTV(TemplateView):
    template_name = 'todo/todo_index.html'

vue-django/VueDjTodo/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}home.html{% endblock %}</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css">
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">

    {% block extra-style %}{% endblock %}

</head>

<body style="padding-top:90px;">

<!-- Main Menu -->
<nav class="navbar navbar-expand-sm navbar-dark bg-primary fixed-top">

    <span class="navbar-brand mx-5 mb-0 font-weight-bold font-italic">Vue-Django System</span>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item mx-1 btn btn-primary">
                <a class="nav-link text-white" href="{% url 'home' %}">Home</a></li>
            <li class="nav-item mx-1 btn btn-primary">
                <a class="nav-link text-white" href="{% url 'todo:index' %}">Todo</a></li>
            <li class="nav-item mx-1 btn btn-primary">
                <a class="nav-link text-white" href="{% url 'home' %}">Blog(todo)</a></li>


            <li class="nav-item dropdown mx-1 btn btn-primary">
                <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">Util</a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a>
                    <div class="dropdown-divider"></div>
                </div>
            </li>
        </ul>

        <form class="form-inline my-2">
            <input class="form-control mr-sm-2" type="search" placeholder="Search">
        </form>

        <ul class="navbar-nav ml-5 mr-5">
            <li class="nav-item dropdown mx-1 btn btn-primary">
                <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">
                    <i class="fas fa-user"></i>&nbsp; Anonymous &nbsp;</a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'home' %}">Login</a>
                    <a class="dropdown-item" href="{% url 'home' %}">Register</a>
                </div>
            </li>
        </ul>

    </div>
</nav>

<div class="container">
    {% block content %}{% endblock %}
</div>

{% block footer %}{% endblock %}

<!-- Bootstrap core JavaScript -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

{% block extra-script %}{% endblock %}

</body>

</html>

vue-django/VueDjTodo/templates/home.html
{% extends 'base.html' %}


{% load static %}

{% block title %}home.html{% endblock %}

{% block extra-style %}
<style type="text/css">

.home-window {
    background-image: url("{% static 'img/lion.jpg' %}");
    background-repeat: no-repeat;
    background-position: center;
    background-size: 100%;
    height: 500px;
    border-top: 10px solid #ccc;
    border-bottom: 10px solid #ccc;
    color: yellow;
    padding: 20px 0 0 20px;
}
.title {
    color: #c80;
    font-weight: bold;
}
.powered {
    position: relative;
    top: 77%;
    color: #cc0;
    font-style: italic;
}

.footer-wrapper {
    background: #456;
    color: #eee;
    line-height: 50px;
}
.footer-wrapper a {
    color: #ff9;    /* footer-right text */
}
.footer-wrapper a:hover {
    color: #0ff;
}
footer ul li {
    text-align: center;
}

</style>
{% endblock extra-style %}

{% block content %}
    <div class="home-window">
        <h2 class="title">Django - Python Web Programming</h2>
        <h4 class="powered"><i class="fas fa-cog"></i> powered by django and bootstrap.</h4>
    </div>

    <hr style="margin: 10px 0;">

    <div class="row text-center">
        <div class="col-sm-6">
            <h3>Todo App</h3>
            <p>With Todo app, you can manage, prioritize, and complete the most important things
                you need to do every day. I can focus on the most important things
                and I can do my day more deliberately.
                You can also share lists with colleagues, friends, and family.</p>
        </div>
        <div class="col-sm-6">
            <h3>Blog App</h3>
            <p>This application makes it possible to log daily events or write your own interests
                such as hobbies, techniques, etc.
                A typical blog combines text, digital images, and links to other blogs, web pages,
                and other media related to its topic.</p>
        </div>
    </div>
{% endblock content %}

{% block footer %}
<footer class="fixed-bottom footer-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <p>Copyright &copy; 2019 DjangoBook by shkim</p>
            </div>
            <div class="col-md-8">
                <ul class="list-inline float-right">
                    <li class="list-inline-item">
                        <a href="#" data-toggle="tooltip" data-placement="top" title="준비중입니다">Introduction</a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#" data-toggle="tooltip" data-placement="top" title="준비중입니다">Help</a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#" data-toggle="tooltip" data-placement="top" title="준비중입니다">Policy</a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#" data-toggle="tooltip" data-placement="top" title="준비중입니다">Something</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>
{% endblock footer %}

{% block extra-script %}
<script>
$(function () {
    $('[data-toggle=tooltip]').tooltip();
});
</script>
{% endblock extra-script %}

vue-django/VueDjTodo/todo/templates/todo/todo_index.html
{% extends 'base.html' %}

{% block title %}todo_index.html{% endblock %}

{% block extra-style %}
    <style>
        body {
            text-align: center;
            background-color: #ddd;
        }
        .inputBox {
            margin: auto;
            width: 70%;
            background: white;
            height: 50px;
            border-radius: 50px;
            line-height: 50px;
        }
        .inputBox .name {
            border-style: none;
            border-bottom: 1px solid #ddd;
            width: 90px;
            padding-left: 20px;
            line-height: 20px;
        }
        .inputBox .item {
            border-style: none;
            border-bottom: 1px solid #ddd;
            width: 400px;
            margin-left: 50px;
            padding-left: 20px;
            line-height: 20px;
        }
        .todoList {
            list-style: none;
            padding: 10px 0;
            text-align: left;
        }
        .todoList li {
            display: flex;
            height: 50px;
            line-height: 50px;
            margin: 0.5rem 0;
            padding: 0 0.9rem;
            background: white;
            border-radius: 5px;
        }
        .removeBtn {
            margin-left: auto;
            font-size: 20px;
        }
        .removeBtn:hover {
            color:red;
        }
    </style>
{% endblock %}

{% block content %}
    <div id = 'app'>

        <h1>My Todo App !</h1>
        <strong>서로 할 일이나 의견을 공유해 봅시다.</strong>
        <br>

        <div class="inputBox">
            <input class="name" v-model.trim="name" type="text" placeholder="name ...">
            <input class="item" v-model.trim="todo" type="text" 
                v-on:keyup.enter="add_todo()" placeholder="type anything welcomed ...">
            <button v-on:click="add_todo()" class="btn btn-primary btn-sm">ADD</button>
        </div>

        <ul class="todoList">
            <li v-for="(todo, index) in todoList">
                <span>[[ todo.name ]]:: [[todo.todo]]</span>
                <span class="removeBtn" v-on:click="remove_todo(todo, index)">x</span>
            </li>
        </ul>
    </div>
{% endblock %}

{% block extra-script %}
    <script src="https://unpkg.com/vue/dist/vue.min.js"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script>
        axios.defaults.xsrfCookieName = 'csrftoken'
        axios.defaults.xsrfHeaderName = 'X-CSRFToken'
       

        var vm = new Vue({
            delimiters: ['[[', ']]'],
            el: '#app',
            data: {
                name:'',
                todo:'',
                todoList:[],
            },
            created: function(){
                console.log("created()...");
                this.fetch_all_todo();
            },
            methods:{
                fetch_all_todo: function(){
                    console.log("fetch_all_todo()...");
                    
                    var vm = this;
                    axios.get('/api/todo/list/')
                    .then(function (res){
                        console.log("GET RES", res);
                        vm.todoList = res.data;
                    })
                    .catch(function (err){
                        console.log("GET ERR", err);
                    })
                },
                add_todo: function(){
                    console.log("add_todo()...");
                    if (this.todo == '') return;
                    if (this.name == '') this.name = '홍길동';

                    var vm = this;
                    var postData = {name: this.name, todo: this.todo};
                    axios.post('/api/todo/create/', postData)
                        .then(function (res){
                            console.log("POST RES", res);
                            vm.todoList.push({id: res.data.id, name: res.data.name, todo: res.data.todo});
                        })
                        .catch(function (err){
                            console.log("POST ERR", err);
                        })

                    this.name = this.todo = '';
                },
                remove_todo: function(todo, index){
                    console.log("remove_todo()...", index);
                    if(confirm("Really delete ?") == false) return;
                    var vm = this;
                    axios.delete('/api/todo/' + todo.id + '/delete/')
                        .then(function(res){
                            console.log("DELETE RES", res);
                            vm.todoList.splice(index, 1);
                        })
                        .catch(function(err){
                            console.log("DELETE ERR", err);
                        })
                },
            },
        })
    </script>
{% endblock %}